/**
 * ManageSpace Extensibility API
 * ManageSpace Extensibility API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExecuteRunFunctionResponse { 
    /**
     * The error response
     */
    name: string;
    /**
     * The error response
     */
    extensionExecutionError: boolean;
    /**
     * Response
     */
    response: object | null;
    /**
     * The error response
     */
    error: string | null;
}

