/**
 * ManageSpace Extensibility API
 * ManageSpace Extensibility API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExtensibilityFunctionRequest { 
    /**
     * The name of the executable code.
     */
    name: string;
    /**
     * The description of the executable code.
     */
    description: string;
    /**
     * The event that triggers this workflow.
     */
    trigger: ExtensibilityFunctionRequest.TriggerEnum;
    /**
     * The code that will run for steps with this external name.
     */
    code: string;
    /**
     * Object version
     */
    versionId?: string;
}
export namespace ExtensibilityFunctionRequest {
    export type TriggerEnum = 'CartUpdateRequested' | 'InvoiceUpdateRequested';
    export const TriggerEnum = {
        CartUpdateRequested: 'CartUpdateRequested' as TriggerEnum,
        InvoiceUpdateRequested: 'InvoiceUpdateRequested' as TriggerEnum
    };
}


