/**
 * ManageSpace Extensibility API
 * ManageSpace Extensibility API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExtensibilityFunctionResponse { 
    /**
     * ID
     */
    extensibilityFunctionId: string;
    /**
     * The name of the executable code.
     */
    name: string;
    /**
     * Version ID
     */
    versionId: string;
    /**
     * Description.
     */
    description: string;
    /**
     * The code that the requested step runs.
     */
    code: string;
}

