/**
 * ManageSpace Extensibility API
 * ManageSpace Extensibility API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImportResponse { 
    /**
     * File name.
     */
    fileName: string;
    /**
     * Location path.
     */
    path: string;
    /**
     * File key.
     */
    key: string;
    /**
     * ETag.
     */
    etag: string;
    /**
     * VersionId.
     */
    versionId: string;
}

