/**
 * ManageSpace Extensibility API
 * ManageSpace Extensibility API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TestExtensionResponse } from './testExtensionResponse';


export interface TestExtension200Response { 
    data?: Array<TestExtensionResponse>;
    success?: boolean;
    error?: object;
}

